# Generated by Django 5.0.6 on 2024-10-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0003_caja_fecha_cierre_alter_caja_monto_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
    ]
