# Generated by Django 5.0.6 on 2024-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0005_remove_detalleventa_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ManyToManyField(to='entidad.producto'),
        ),
    ]
