# Generated by Django 5.0.6 on 2024-10-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0006_detalleventa_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
    ]
