# Generated by Django 5.0.6 on 2024-10-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0007_remove_detalleventa_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaXProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('descrp', models.CharField(max_length=10)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.detalleventa')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidad.producto')),
            ],
            options={
                'verbose_name': 'Detalles Ventas Productos',
            },
        ),
    ]
