# Generated by Django 5.0.6 on 2024-10-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0008_detalleventaxproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVentaXProducto',
        ),
    ]
