# Generated by Django 5.0.6 on 2024-10-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0010_detalleventaxproducto_detalleventa_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventaxproducto',
            name='descrp',
        ),
    ]
