# Generated by Django 5.0.6 on 2024-10-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0014_movimientocaja_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='decuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
