# Generated by Django 5.0.6 on 2024-10-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0015_venta_decuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='decuento',
            new_name='descuento',
        ),
    ]
