# Generated by Django 5.0.6 on 2024-11-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0016_rename_decuento_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
