# Generated by Django 5.0.6 on 2024-11-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0017_categoria_activo_producto_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='proveedores',
        ),
    ]
