# Generated by Django 5.0.6 on 2024-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0019_accesousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesousuario',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
