# Generated by Django 5.0.6 on 2024-11-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0020_accesousuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorproducto',
            name='telefono',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
