# Generated by Django 5.0.6 on 2024-11-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0021_alter_proveedorproducto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorproducto',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
