# Generated by Django 5.1 on 2025-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0023_delete_ciudad_alter_cliente_correo_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
