# Generated by Django 5.1 on 2025-05-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0024_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], default='unidad', max_length=10),
        ),
    ]
