# Generated by Django 5.1 on 2025-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0026_alter_venta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='forma_pago',
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago_1',
            field=models.CharField(blank=True, choices=[('TRAN', 'TRANSFERENCIA'), ('EFEC', 'EFECTIVO'), ('TARJ', 'TARJETA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('TRAN', 'TRANSFERENCIA'), ('EFEC', 'EFECTIVO'), ('TARJ', 'TARJETA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pago_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pago_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
