# Generated by Django 5.2 on 2025-05-26 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0027_remove_venta_forma_pago_venta_metodo_pago_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='accesousuario',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accesousuario',
            name='hora_ingreso',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.sucursal'),
            preserve_default=False,
        ),
    ]
