# Generated by Django 5.2 on 2025-05-26 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0028_sucursal_alter_accesousuario_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad.sucursal'),
        ),
    ]
