# Generated by Django 5.1 on 2025-05-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0029_alter_caja_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='TEMP', max_length=50),
        ),
    ]
