# Generated by Django 5.1 on 2025-05-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0030_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
