# Generated by Django 5.1 on 2025-06-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0031_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventaxproducto',
            options={'verbose_name': 'Detalle Venta Producto', 'verbose_name_plural': 'Detalles Ventas Productos'},
        ),
        migrations.AddField(
            model_name='detalleventaxproducto',
            name='cantidad_original',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventaxproducto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventaxproducto',
            name='unidad_venta',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], default='unidad', max_length=10),
        ),
        migrations.AlterField(
            model_name='detalleventaxproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
