# Generated by Django 5.1 on 2025-06-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0032_alter_detalleventaxproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventaxproducto',
            options={'verbose_name': 'Detalles Ventas Productos'},
        ),
        migrations.RemoveField(
            model_name='detalleventaxproducto',
            name='cantidad_original',
        ),
        migrations.RemoveField(
            model_name='detalleventaxproducto',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detalleventaxproducto',
            name='unidad_venta',
        ),
        migrations.AlterField(
            model_name='detalleventaxproducto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
