# Generated by Django 5.1 on 2025-06-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0034_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventaxproducto',
            name='precio_unitario_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventaxproducto',
            name='subtotal_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
