# Generated by Django 5.2 on 2025-12-29 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0035_detalleventaxproducto_precio_unitario_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Activar/desactivar notificaciones automáticas')),
                ('mensaje_template', models.TextField(default='¡Hola {nombre}! 🎉 Has ganado {puntos} puntos en tu compra. Ahora tienes {total_puntos} puntos acumulados. ¡Gracias por tu preferencia!', help_text='Plantilla del mensaje. Variables: {nombre}, {puntos}, {total_puntos}, {monto}')),
                ('enviar_en_venta', models.BooleanField(default=True, help_text='Enviar notificación automáticamente al realizar una venta')),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Account SID de Twilio', max_length=100)),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Auth Token de Twilio', max_length=100)),
                ('twilio_whatsapp_from', models.CharField(default='whatsapp:+14155238886', help_text='Número de WhatsApp de Twilio (formato: whatsapp:+14155238886)', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('email_cliente', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('descripcion', models.CharField(default='Transferencia', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mostrada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RangoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_minimo', models.DecimalField(decimal_places=2, help_text='Monto mínimo de la compra', max_digits=10)),
                ('monto_maximo', models.DecimalField(decimal_places=2, help_text='Monto máximo de la compra', max_digits=10)),
                ('puntos_otorgados', models.IntegerField(help_text='Cantidad de puntos que se otorgan en este rango')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, este rango se aplicará')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rango de Puntos',
                'verbose_name_plural': 'Rangos de Puntos',
                'ordering': ['monto_minimo'],
            },
        ),
        migrations.AlterModelOptions(
            name='detalleventaxproducto',
            options={'verbose_name': 'Detalle Venta Producto', 'verbose_name_plural': 'Detalles Ventas Productos'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultima_actualizacion_puntos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='puntos_actuales',
            field=models.IntegerField(default=0, help_text='Puntos disponibles del cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='puntos_totales_acumulados',
            field=models.IntegerField(default=0, help_text='Total de puntos ganados históricamente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='puntos_otorgados',
            field=models.IntegerField(default=0, help_text='Puntos otorgados en esta venta'),
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GANADO', 'Puntos Ganados'), ('CANJEADO', 'Puntos Canjeados'), ('AJUSTE', 'Ajuste Manual'), ('VENCIDO', 'Puntos Vencidos')], max_length=10)),
                ('cantidad', models.IntegerField(help_text='Cantidad de puntos (positivo o negativo)')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del movimiento')),
                ('saldo_resultante', models.IntegerField(help_text='Saldo de puntos después de este movimiento')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to='entidad.cliente')),
                ('empleado', models.ForeignKey(blank=True, help_text='Empleado que registró el movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, help_text='Venta relacionada si los puntos fueron ganados por compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entidad.venta')),
            ],
            options={
                'verbose_name': 'Historial de Puntos',
                'verbose_name_plural': 'Historial de Puntos',
                'ordering': ['-fecha'],
            },
        ),
    ]
