# Generated by Django 5.2 on 2025-12-29 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0036_configuracionnotificaciones_notificacionpago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionNotificaciones',
        ),
        migrations.AlterField(
            model_name='historialpuntos',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialpuntos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historialpuntos',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialpuntos',
            name='saldo_resultante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialpuntos',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entidad.venta'),
        ),
        migrations.AlterField(
            model_name='rangopuntos',
            name='activo',
            field=models.BooleanField(default=True, help_text='Solo rangos activos se aplicarán'),
        ),
        migrations.AlterField(
            model_name='rangopuntos',
            name='puntos_otorgados',
            field=models.IntegerField(help_text='Cantidad de puntos que se otorgan'),
        ),
    ]
